apiVersion: v1
kind: ConfigMap
metadata:
  name: env
  #namespace: default
data:
  mysql_pass: "root"
  mysql_user: "root"
  mysql_root_password: "root"
  db_users: "users"
  redis_host: "redis://redis.default.svc.cluster.local:6379"