apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: default
spec:
  selector:
    app: redis-pod
  type: ClusterIP
  ports:
  - name: redis-port
    protocol: TCP
    port: 6379
    targetPort: 6379 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-dep
  #namespace: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-pod
  template:
    metadata:
      labels:
        app: redis-pod
    spec:
      containers:
        - name: redis-container
          image: redis:6.2.6-alpine
          ports:
            - containerPort: 6379
              name: redis
      #     volumeMounts:
      #       - name: redis-persistent-storage
      #         mountPath: /data
      # volumes:
      #   - name: redis-persistent-storage
      #     persistentVolumeClaim:
      #       claimName: redis-pv-claim
          