# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: local-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
#---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv-auth
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: local-storage
  hostPath:
    path: "/mnt/c/users/Kader.DZL-41D5HK3/Desktop/microservice/auth/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: auth-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: default
spec:
  selector:
    app: auth-db-pod
  type: ClusterIP
  ports:
  - name: auth-mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306 
---
apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  namespace: default
spec:
  selector:
    app: auth-db-pod
  type: ClusterIP
  ports:
  - name: auth-db-port
    protocol: TCP
    port: 3306
    targetPort: 3306 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-db-dep
  #namespace: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-db-pod
  template:
    metadata:
      labels:
        app: auth-db-pod
    spec:
      containers:
        - name: auth-db-container
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: auth
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              name: mysql-auth
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: auth-pv-claim
