apiVersion: apps/v1
kind: Deployment
metadata:
  name:  users-dep
spec:
  selector:
    matchLabels:
      app: users-pod
  template:
    metadata:
      labels:
        app:  users-pod
    spec:
      containers:
      - name:  users-container
        image:  okirim/users-dev:latest
        env:
          - name: REDIS_HOST
            valueFrom:
              configMapKeyRef:
                name: env
                key: redis_host
        command: ["npm","run","start:debug"]
        ports:
        - containerPort:  3000
          name:  users
---
apiVersion: v1
kind: Service
metadata:
  name: users
  #namespace: ingress-nginx
spec:
  selector:
    app: users-pod
  ports:
  - name: users
    port: 3000
    protocol: TCP
    targetPort: 3000
---
#   kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.1/deploy/static/provider/cloud/deploy.yaml
#   kubectl delete -A ValidatingWebhookConfiguration ingress-nginx-admission
#   kubectl get services -n ingress-nginx