# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: local-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
#---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  # storageClassName: local-storage
  hostPath:
    path: "/mnt/c/Users/Kader.DZL-41D5HK3/Desktop/microservice/users/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: users-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: users-svc
  namespace: default
spec:
  selector:
    app: users-db-pod
  type: ClusterIP
  ports:
  - name: users-mysql-port
    protocol: TCP
    port: 3306
    targetPort: 3306 
---
apiVersion: v1
kind: Service
metadata:
  name: users-svc
  namespace: default
spec:
  selector:
    app: users-db-pod
  type: ClusterIP
  ports:
  - name: users-db-port
    protocol: TCP
    port: 3306
    targetPort: 3306 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-db-dep
  #namespace: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-db-pod
  template:
    metadata:
      labels:
        app: users-db-pod
    spec:
      containers:
        - name: users-db-container
          image: mysql:8.0
          env:
            - name: MYSQL_DATABASE
              value: users
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASSWORD
              value: root
          ports:
            - containerPort: 3306
              name: mysql-users
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: users-pv-claim
